version: '3'

services:
  db:
    image: postgres:9.6
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    env_file:
      - api.env

  web:
    build: .
    command: bash -c "dockerize -wait tcp://db:5432 -timeout 1m && ./run.sh"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db