# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-03 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180403_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='agent_string',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
