# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-03 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180403_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Agent'),
        ),
        migrations.AlterField(
            model_name='request',
            name='ip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.IP'),
        ),
        migrations.AlterField(
            model_name='request',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Url'),
        ),
        migrations.AlterField(
            model_name='request',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.CustomUser'),
        ),
    ]
