# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-03 15:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180403_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='url',
        ),
    ]
